#!/bin/bash

mvn clean
mvn package
sshpass -p "$WOWRAIDAPI_DEPLOY_PASSWORD" scp target/wowraid-api-*.jar $WOWRAIDAPI_DEPLOY_USER@$WOWRAIDAPI_DEPLOY_HOST:$WOWRAIDAPI_DEPLOY_DIRECTORY/
sshpass -p "$WOWRAIDAPI_DEPLOY_PASSWORD" ssh $WOWRAIDAPI_DEPLOY_USER@$WOWRAIDAPI_DEPLOY_HOST $WOWRAIDAPI_DEPLOY_DIRECTORY/deploy-wowraid.sh
