spring:
  security:
    oauth2:
      client:
        registration:
          battlenet:
            provider: battlenet
            client-id: 5f07749cb34149de989c34d9e904ef8a
            client-secret: L3Cs6D7YwhDJOKYcodiU53eQqT8ybvPE
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
        provider:
          battlenet:
            issuer-uri: "https://eu.battle.net/oauth"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
        enable_lazy_load_no_trans: true
