spring:
  security:
    oauth2:
      client:
        registration:
          google:
            provider: battlenet
            client-id: 5f07749cb34149de989c34d9e904ef8a
            client-secret: L3Cs6D7YwhDJOKYcodiU53eQqT8ybvPE
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
        provider:
          battlenet:
            issuer-uri: https://eu.battle.net/oauth
